version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - dev-static:/vol/web
    command: >
      sh -c "
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=django
      - DB_USER=admin
      - DB_PASS=admin
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - django-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  
volumes:
  django-db:
  dev-static:



      
  